name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Buildozer
      run: |
        pip install buildozer
        buildozer init
        echo '[app]
title = Мячик Баскетбол
package.name = myachikbasket
package.domain = com.antoha
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf,mp3,wav,ogg
version = 1.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
android.api = 30
android.minapi = 21
android.sdk = 23
android.ndk = 23b
android.accept_sdk_license = True' > buildozer.spec
    
    - name: Build APK
      run: buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Мячик-APK
        path: bin/*.apk
